module.exports = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  MONGO_URI: process.env.MONGO_URI,
  COOKIE_KEY: process.env.COOKIE_KEY,
  REDIRECT_DOMAIN: process.env.REDIRECT_DOMAIN
};
